project:
  type: website
  output-dir: docs
  preview: 
    port: 4200
  
website:
  page-navigation: true
  title: "Ahyeong website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog.qmd
        text: Posts
        
format:
  html:
    theme: journal
    css: styles.css
    toc: true
editor: visual
