---
title: "EasyPython Practice Ch8"
author: Ahyeong Jeong
date: "2024-07-22"
categories: [EasyPython]
---

# Ch8 문제 풀이 

필요한 패키지 불러오기 
```{python}
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
```


데이터 불러오기 
```{python}
mpg = pd.read_csv('C:/Users/USER/Documents/LS 빅데이터 스쿨/myportfolio/data/mpg.csv')
```

## p.204
`mpg`데이터와 `midwest` 데이터를 이용해 분석문제를 해결해 보세요.

#### Q1. `mpg` 데이터의 `cty`와 `hwy`간에 어떤 관계가 있는지 알아보려고 합니다. 
x축은 `cty, y축은 `hwy`로 된 산점도를 만들어 보세요
```{python}
sns.scatterplot(data = mpg, x = 'cty', y = 'hwy')
plt.show()
```

#### Q2. 
미국의 지역별 인구통계 정보를 담은 `midwest.csv`를 이용해 전체 인구와 아시아인 인구 간에 어떤 관계가 있는지 알아보려고 합니다. x축은 `poptotal`(전체인구), y축은 `popasian`(아시아인 인구)으로 된 산점도를 만들어보세요. 전체 인구는 50만 명 이하, 아시아인 인구는 1만 명 이하인 지역만 산점도에 표시되게 설정하세요.
```{python}
midwest = pd.read_csv('C:/Users/USER/Documents/LS 빅데이터 스쿨/Doit_Python/data/midwest.csv')
plt.clf()
sns.scatterplot(data = midwest, x = 'poptotal', y = 'popasian')\
   .set(xlim = [0, 500000], ylim = [0, 10000])
plt.show()
```

## p.211
`mpg`데이터를 이용해 분석 문제를 해결해보세요
#### Q1.
어떤 회사에서 생산한 `suv` 차종의 도시 연비가 높은지 알아보려고 합니다. `suv`차종을 대상으로 `cty`(도시 연비) 평균이 가장 높은 회사 다섯 곳을 막대 그래프로 표현해 보세요. 막대는 연비가 높은 순으로 정렬하세요. 

```{python}
mpg.head()
# 차종이 suv인 데이터 프레임 만들기 
suv = mpg.query("category == 'suv'")
# 회사 별 cty 연비 구하기 
df1 = suv.groupby('manufacturer', as_index = False) \
        .agg(cty_mean = ('cty', 'mean')) \
        .sort_values('cty_mean', ascending = False) \
        .head()
        
#막대그래프
plt.clf()
sns.barplot(data = df1, x = 'manufacturer', y = 'cty_mean', hue = 'manufacturer')
plt.show()
```

## Q2. 
자동차 중에 어떤 `category`가 많은지 알아보려고 합니다. `sns.barplot()`을 이용해 자동차 종류별 빈도를 표현한 막대 그래프를 만들어 보세요. 막대는 빈도가 높은 순으로 정렬하세요. 
```{python}
df2 = mpg.groupby('category', as_index = False) \
         .agg(category_n = ('category', 'count')) \
         .sort_values('category_n')
df2
plt.clf()
sns.barplot(data = df2, x = 'category', y = 'category_n', hue = 'category')
plt.show()
```

## p.217
`economics` 데이터를 이용해 분석 문제를 해결해보세요
#### Q1. 
`psavert`가 시간에 따라 어떻게 변해 왔는지 알아보려고 합니다. 연도별 개인 저축률의 변화를 나타낸 시계열 그래프를 만들어 보세요. 
```{python}
economics = pd.read_csv('C:/Users/USER/Documents/LS 빅데이터 스쿨/myportfolio/data/economics.csv')
economics['date2'] = pd.to_datetime(economics['date'])
economics['year'] = economics['date2'].dt.year
economics.head()
plt.clf()
sns.lineplot(data = economics, x = 'year', y = 'psavert', errorbar = None)
plt.show()
```

#### Q2.
2014년 월별 `psavert`의 변화를 나타낸 시계열 그래프 만들어 보세요.
```{python}
economics['month'] = economics['date2'].dt.month
year_2014 = economics.query('year == 2014')
plt.clf()
sns.lineplot(data = year_2014, x = 'month', y = 'psavert')
plt.show()
```

## p.220
`mpg` 데이터를 이용해 분석 문제를 해결해 보세요.

#### Q1.
`category`가 `compact`, `subcompact`, `suv`인 자동차의 `cty`가 어떻게 다른지 비교해 보려고 합니다. 세 차종의 `cty`를 나타낸 상자 그림을 만들어 보세요. 
```{python}
mpg1 = mpg.query("category in ['compact', 'subcompact', 'suv']")
plt.clf()
sns.boxplot(data = mpg1, x = 'category', y = 'cty', hue = 'category')
plt.show()
```




